package org.example.drools;

import org.server.Person;

rule "Adult age"
    when
        $p : Person(age > 18)
    then
        System.out.println("Rule triggered: age > 18 (adult)");
        modify($p) { setAdult(true) }
end

rule "Minor age"
    when
        $p : Person(age <= 18)
    then
        System.out.println("Rule triggered: age <= 18 (minor)");
        modify($p) { setAdult(false) }
end

rule "Name is John"
    when
        $p : Person(getName() == "John")
    then
        System.out.println("Rule triggered: name is John");
        modify($p) { setIsName(true) }
end

rule "Name is not John"
    when
        $p : Person(getName() != "John")
    then
        System.out.println("Rule triggered: name is not John");
        modify($p) { setIsName(false) }
end

rule "School age child"
    when
        $p : Person(age >= 6 && age <= 18)
    then
        System.out.println($p.getName() + " is school-aged");
end

rule "Kindergarten age child"
    when
        $p : Person(age > 3 && age < 6)
    then
        System.out.println($p.getName() + " is in kindergarten age");
end

rule "Infant"
    when
        $p : Person(age <= 3)
    then
        System.out.println($p.getName() + " is an baby");
end
